### ISSUE TITLE
Please upload "taxationistheftbot.js" unminify.

### ISSUE THREAD

**Issue by eliooses** [bitbutter/ExploreIsTaxationTheft#2]
Hi @bitbutter congratulations & thanks for you new project.

I want translate this, and make pull request for language navigation. But is very difficult with the minify version of "taxationistheftbot.js".

If you can upload will be great.

Thanks a lot.

Best regards from Buenos Aires.

**Comment by bitbutter** [comment]
Nice avatar!

Hi. Yes, this might be difficult. I'm using the Inky editor to work on the script, and it only exports minified .js

How did you see the language navigation working?

In general the best approach for translation is probably to duplicate the .ink file and use Inky to translate it to new languages, then export .js files for those languages.

One other thing: in the next few days/weeks there'll likely be many small changes, perhaps some bigger ones too. You might want to hold off for a while if you want to get the benefit of those upcoming edits.
