### ISSUE TITLE
Suggestion: Link to resources at the end

### ISSUE THREAD

**Issue by Buddybenj** [bitbutter/ExploreIsTaxationTheft#6]
Perhaps if the person still isn't convinced that taxation is theft, he could be given links to videos or books that might convince him of other libertarian ideas.

If the person agrees that taxation is theft, he will most likely want to know if an how society can function without taxes. Again, maybe he could be given links to videos or books that explain it.

**Comment by bitbutter** [comment]
I used to have links at the end. No one was using them so it was removed to simplify things. Might re-add later.
